---
title: "Overview"
output:
  html_document:
    toc: false
---

This project aims to study the depletion of bases in DNA sequence and its visualization. Transcription factor binding site is characterized by the DNA sequence motifs. A powerful tool to visualize the motif is logo plot. Usually, the enrichment is highlighted while the depletion is usually overlooked. Here, we introduce negative logo plot, where the depletion is plotted down below the zero on y axis so that we can find both strong positive and negative effects.

The plots are generated by the R package, Logolas. See [GitHub](https://github.com/kkdey/Logolas) or [Bioconductor](https://bioconductor.org/packages/release/bioc/html/Logolas.html) for details. 

The analysis related to Dirichlet adaptive shrinkage is done by the R package, dash. See [GitHub](https://github.com/kkdey/dash).

These are results of the analysis.

1. [Negative logo plot: a new visualization.](neg_logo_plot.html)
2. [EDA: insight of the data.](ColSums_of_PFM.html)
3. [Depletion: the oppsite of enrichment.](Depletion.html)
4. [Dimer: an interesting finding.](dimer.html)
5. [Dirichlet adaptive shrinkage: small sample size matters.](dashkk.html)
6. [The power of dash: illustrative examples.](dashex.html)
7. [Cancer Mutation Signature: a new view.](mutation.html)
8. [Consensus sequence: an informative way.](consensus_seq.html)
9. [Plant Motif: dealing with background probability.](plant.html)
10.[Protein Motif: more logos, more challenge](proteinplot.html)

All the results here are reproducible. See [here](datasource.html) for the list of data sources. The code could be found in the Rmarkdown files under analysis folder and the data are in the data folder in the github repository. 

#Credits

Thanks to [Kushal K Dey](https://kkdey.github.io/), [Matthew Stephens](http://stephenslab.uchicago.edu/), [John Blischak](https://github.com/jdblischak), and [	Hussein Al-Asadi](https://halasadi.wordpress.com/) for their great help.
